name: Crear y subir imagen de docker file
on: 
  push:
    branches:
      - main

jobs:
  publish_images:
    runs-on: ubuntu-latest
    environment: docker
    steps: 
      - name: checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        run: echo "${{ secrets.token }}" | docker login -u "${{ secrets.user }}" --password-stdin
      - name: construir imagen
        run:  docker build . -t nulld12/api-usuarios:latest
      - name: subir imagen a docker
        run:  docker push nulld12/api-usuarios:latest  